site:
  title: Antora Extension Demo Site
  # the 404, site-map, and canonical urls are only generated when a URL is defined
  url: https://ahus1.github.io/antora-extensions-demo
  start_page: ROOT::index.adoc
content:
  sources:
    - url: ..
      start_paths:
        - docs/content_v1
        - docs/content_v2
        - docs/startpage
      branches:
        - 'HEAD'

urls:
  latest_version_segment: current
  html_extension_style: drop

antora:
  extensions:
    - '@antora/lunr-extension'
    - '@antora/collector-extension'
    - '@antora/pdf-extension'
    - lib/frontmatter.js

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental_ui
  output_dir: _antora/antora-extensions-demo

runtime:
  fetch: true
  cache_dir: ./.cache/antora
  log:
    failure_level: error

output:
  clean: true
  dir: _site/antora-extensions-demo

# Global asciidoc attributes here, used across all versions of documentation
asciidoc:
  extensions:
    - asciidoctor-kroki
    # Antora will resolve extensions listed here that end with something that looks like a file name extension as files relative to the project's folder
    # therefore append the slash
    - asciidoctor-highlight.js/
  attributes:
    kroki-fetch-diagram: true
    idprefix: ''
    idseparator: '-'
    source-highlighter: highlightjs-ext
    page-version-current: '2.0'
    skip-front-matter: ''

